version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env.docker
        environment:
            COMPOSER_ALLOW_SUPERUSER: "1"
        volumes:
            - .:/app
            - /app/vendor
        depends_on:
            mysql:
                condition: service_healthy
        restart: unless-stopped

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - .:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        restart: unless-stopped

    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "app", "-psecret"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    cron:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env.docker
        environment:
            COMPOSER_ALLOW_SUPERUSER: "1"
        volumes:
            - .:/app
            - /app/vendor
        depends_on:
            mysql:
                condition: service_healthy
            php:
                condition: service_started
        restart: unless-stopped
        command: /app/docker/scripts/cron-start.sh

volumes:
    mysql_data:
